### ISSUE TITLE
sampling functionality

### ISSUE THREAD

**Issue by geotheory** [coolbutuseless/dplyr-cli#11]
Possible idea - I wonder if `sample_xx` and/or a systematic (equal interval) sampling might be desirable to implement?  Of course it can be achieved with `grep` and other bash functions but many R users won't know how to do this.

**Comment by coolbutuseless** [comment]
`sample_n` works for me: ```cat mtcars.csv | dplyr sample_n 10 | dplyr kable```

Or do you mean something else?

**Comment by geotheory** [comment]
Ah my bad. Misread the docs
