### ISSUE TITLE
Installation via conda?

### ISSUE THREAD

**Issue by dlaehnemann** [coolbutuseless/dplyr-cli#13]
Hi @coolbutuseless ,

cool idea, and very useful. Have you considered `conda` as an installation option? Contributing a respective recipe to `conda-forge`, the community-maintained repository of `conda` recipes for software installations is really easy (especially when further looking at code for existing recipes/feedstocks that are similar) :
https://conda-forge.org/#add_recipe

And all the respective `R` packages are available as `conda-forge` packages / feedstocks:
https://conda-forge.org/feedstocks/

As a result, for anyone who has [`miniconda` installed](https://docs.conda.io/en/latest/miniconda.html), installation into an isolated environment and including all dependencies would be as easy as:

```
conda create -n dplyr-cli-env dplyr-cli
```

And for using it, you simply activate that environment:
```
conda activate dplyr-cli-env
```

**Comment by dlaehnemann** [comment]
Hi again @coolbutuseless ,

a nice first step to creating such a recipe would be to create a versioned GitHub release for the latest release you made. It's as easy as heading over to [https://github.com/coolbutuseless/dplyr-cli/releases](https://github.com/coolbutuseless/dplyr-cli/releases) and naming the release with the respective version number. This provides for a stable link to a bundled archive of the particular release and it should then be easy to create a `conda-forge` package.

And I'd be willing to help out on that, just to have a convenient and reproducible way of installing this nice CLI tool! Let me know if you need any more infos or pointers.

**Comment by coolbutuseless** [comment]
I've tagged the current version as 'v0.1.3' - https://github.com/coolbutuseless/dplyr-cli/releases/tag/v0.1.3

If you'd like to make progress on conda installation, I'm happy to help if I can, but this is not a priority for me.
