### ISSUE TITLE
Support for multiple function arguments?

### ISSUE THREAD

**Issue by shenwei356** [coolbutuseless/dplyr-cli#17]
Hi, I'm trying to call `transmute_at ` which needs more than one argument. 

    cat data.csv | dplyr transmute_at -c '"X"'  'function(x){-x}'

But it's not supported by passing the two according to command line cause they are [pasted](https://github.com/coolbutuseless/dplyr-cli/blob/master/dplyr#L120):

    code <- paste(opt$code, collapse="")

And I also tried passing one list containing the two arguments, but failed too.

    cat data.csv | dplyr transmute_at -c  'as.list(c("X"), as.function(as.list("function(x){-x}")))'

**Comment by albertotb** [comment]
This is not a solution to the general problem, but it works for this specific case. With dplyr 1.0, coming out soon, you can do (the `*_at` variants are mostly being replaced by `across`) :

```
cat data.csv | dplyr transmute -c 'across(X, function(x){-x})'
```

If you want to try it out you can install the release candidate of dplyr 1.0 with:

```
remotes::install_github("tidyverse/dplyr")
```

**Comment by coolbutuseless** [comment]
Hi @shenwei356 - the simplicity of the CLI interface in `dplyr-cli` means that `transmute_at` isn't currently supported, this is unlikely to change.

I would follow @albertotb's suggestion and upgrade to dplyr 1.0 with `across()`

**Comment by shenwei356** [comment]
Thank you all!
