### ISSUE TITLE
`lr` on shebang line: install?

### ISSUE THREAD

**Issue by mpettis** [coolbutuseless/dplyr-cli#3]
The first line is

    #!/usr/bin/env lr

Is the install of the `littler` package supposed to install this binary?  If so, it didn't for me.  Is there a separate install for the `lr` binary?

**Comment by bitsandbricks** [comment]
I think lr is the alias for r if you use a mac

If you are using Linux like me, try replacing that line with

#!/usr/bin/env r

**Comment by mpettis** [comment]
Thank you.  I also found these instructions for littler that match what @bitsandbricks mentioned.  I'll consider this closed.  https://cran.r-project.org/web/packages/littler/vignettes/littler-faq.html
