### ISSUE TITLE
"No such file or directory" on Mac

### ISSUE THREAD

**Issue by geotheory** [coolbutuseless/dplyr-cli#7]
Am I doing something wrong here?

```
$ ls -la
total 16
drwxr-xr-x    4 me  staff   128B 21 Apr 00:49 .
drwxr-xr-x@ 141 me  staff   4.4K 21 Apr 00:49 ..
-rwxr-xr-x@   1 me  staff   3.8K 21 Apr 00:36 dplyr.sh
-rw-r--r--    1 me  staff   1.3K 21 Apr 00:13 mtcars.csv
$ wc -l *
     118 dplyr.sh
      33 mtcars.csv
     151 total
$ cat mtcars.csv | ./dplyr.sh filter -c mpg == 21
env: lr: No such file or directory
```

**Comment by coolbutuseless** [comment]
After installing `littler` you need to move the executable to your seaarch path.

I've added some more instructions to the README, can you see if that helps you?

**Comment by coolbutuseless** [comment]
Now that `dplyr-cli` is using 'Rscript' instead of 'littler' this should not be an issue anymore. Please re-open if the new version does not work for you.

**Comment by geotheory** [comment]
Fixed cheers :)
