### ISSUE TITLE
zsh: = not found

### ISSUE THREAD

**Issue by aborruso** [coolbutuseless/dplyr-cli#8]
Hi,
starting from this

```
a,b
2,3
4,5
```

and running `cat input.csv | ./dplyr.sh filter -c a == 2` I have

```
zsh: = not found
[1]    315 broken pipe  cat input.csv
```

Thank you for this great idea and tool

**Comment by coolbutuseless** [comment]
Could you try quoting the code that goes to filter and report back?  i.e.

```cat input.csv | ./dplyr.sh filter -c "a == 2"```

**Comment by aborruso** [comment]
Hi @coolbutuseless , I have tested

```
cat input.csv | ./dplyr.sh filter -c "a == 2"
```

and I have notified that I do not have `readr`. I have installed it running

```
sudo su - -c "R -e \"install.packages('readr', repos='http://cran.rstudio.com/')\""
```

And now it works, thank you.

I'm not closing it, because you probably want to edit example 1 of the README.
