### ISSUE TITLE
error

### ISSUE THREAD

**Issue by EdenGoldfarb** [coolbutuseless/dplyr-cli#9]
Hi there! Thanks a lot for this one!

I'm getting this error.  Am I doing something wrong?

$ cat mtcars.csv | ./dplyr.sh filter -c mpg == 21

Error: '"mpg","cyl","disp","hp","drat","wt","qsec","vs","am","gear","carb"21,6,160,110,3.9,2.62,16.46,0,1,4,421,6,160,110,3.9,2.875,17.02,0,1,4,422.8,4,108,93,3.85,2.32,18.61,1,1,4,121.4,6,258,110,3.08,3.215,19.44,1,0,3,118.7,8,360,175,3.15,3.44,17.02,0,0,3,218.1,6,225,105,2.76,3.46,20.22,1,0,3,114.3,8,360,245,3.21,3.57,15.84,0,0,3,424.4,4,146.7,62,3.69,3.19,20,1,0,4,222.8,4,140.8,95,3.92,3.15,22.9,1,0,4,219.2,6,167.6,123,3.92,3.44,18.3,1,0,4,417.8,6,167.6,123,3.92,3.44,18.9,1,0,4,416.4,8,275.8,180,3.07,4.07,17.4,0,0,3,317.3,8,275.8,180,3.07,3.73,17.6,0,0,3,315.2,8,275.8,180,3.07,3.78,18,0,0,3,310.4,8,472,205,2.93,5.25,17.98,0,0,3,410.4,8,460,215,3,5.424,17.82,0,0,3,414.7,8,440,230,3.23,5.345,17.42,0,0,3,432.4,4,78.7,66,4.08,2.2,19.47,1,1,4,130.4,4,75.7,52,4.93,1.615,18.52,1,1,4,233.9,4,71.1,65,4.22,1.835,19.9,1,1,4,121.5,4,120.1,97,3.7,2.465,20.01,1,0,3,115.5,8,318,150,2.76,3.52,16.87,0,0,3,215.2,8,304,150,3.15,3.435,17.3,0,0,3,213.3,8,350,245,3.73,3.84,15.41,0,0,3,419.2,8,400,175,3.
In addition: Warning messages:
1: In if (grepl("\n", x)) { :
  the condition has length > 1 and only the first element will be used
2: In if (grepl("\n", path)) return(path) :
  the condition has length > 1 and only the first element will be used
3: In if (is_url(path)) { :
  the condition has length > 1 and only the first element will be used
4: In if (file.exists(path)) return(normalizePath(path, "/", mustWork = FALSE)) :
  the condition has length > 1 and only the first element will be used
5: In if (!is_absolute_path(path)) paste0(" in current working directory ('",  :
  the condition has length > 1 and only the first element will be used

**Comment by coolbutuseless** [comment]
What OS and shell are you using?

Can you try the following?:  ```dplyr filter --file=mtcars.csv -c "cyl == 8"```

**Comment by EdenGoldfarb** [comment]
$ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.3.1611 (Core)
Release:        7.3.1611

shell: bash

tried this:
./dplyr.sh filter --file=mtcars.csv -c "cyl == 8"

and still getting the same error.

**Comment by coolbutuseless** [comment]
Hmmm.  Can you do a fresh clone? I've update the script to use Rscript instead of littler.


If it still fails, can you tell me: 

```packageVersion("dplyr")```
```packageVersion("readr")```
```packageVersion("docopt")```

**Comment by EdenGoldfarb** [comment]
Still getting the same error :(

> packageVersion("readr")
[1] ‘1.1.1’
> packageVersion("dplyr")
[1] ‘0.8.5’
> packageVersion("docopt")
[1] ‘0.6.1’

Thanks :)

**Comment by coolbutuseless** [comment]
I'm running out of ideas.  Run with verbose flag - `-v`

Try updating your `readr` - mine is 1.3.1

**Comment by SantoshSrinivas79** [comment]
hello @coolbutuseless .. I am still facing this issue on the latest R and latest packages

![Screenshot 2022-01-04 at 6 10 35 PM](https://user-images.githubusercontent.com/1036163/148060528-1a0fc01c-cb1c-4301-aab4-88aa088e56ac.png)

**Comment by jmcastagnetto** [comment]
OK, it is a simple fix, as per the current documentation for readr::read_csv() (https://readr.tidyverse.org/reference/read_delim.html)

> ...  To be recognised as literal data, the input must be either wrapped with I(), be a string containing at least one new line, or be a vector containing at least one string with a new line. ...

So in https://github.com/coolbutuseless/dplyr-cli/blob/d20f40f403004adbfaa8a09b65559804ef8d6ba3/dplyr#L95

It should be:

```r
    .data <- readr::read_csv(I(input), col_types = readr::cols())
```

With that change the following three equivalent commands, work:

```bash
$ cat mtcars.csv | dplyr --verbose --csv filter "cyl == 8"
------------------------------------------
[input] reading CSV from stdin
command: dplyr::filter(.data, cyl == 8)
>>>> output CSV to stdout
"mpg","cyl","disp","hp","drat","wt","qsec","vs","am","gear","carb"
18.7,8,360,175,3.15,3.44,17.02,0,0,3,2
14.3,8,360,245,3.21,3.57,15.84,0,0,3,4
16.4,8,275.8,180,3.07,4.07,17.4,0,0,3,3
17.3,8,275.8,180,3.07,3.73,17.6,0,0,3,3
15.2,8,275.8,180,3.07,3.78,18,0,0,3,3
10.4,8,472,205,2.93,5.25,17.98,0,0,3,4
10.4,8,460,215,3,5.424,17.82,0,0,3,4
14.7,8,440,230,3.23,5.345,17.42,0,0,3,4
15.5,8,318,150,2.76,3.52,16.87,0,0,3,2
15.2,8,304,150,3.15,3.435,17.3,0,0,3,2
13.3,8,350,245,3.73,3.84,15.41,0,0,3,4
19.2,8,400,175,3.08,3.845,17.05,0,0,3,2
15.8,8,351,264,4.22,3.17,14.5,0,1,5,4
15,8,301,335,3.54,3.57,14.6,0,1,5,8

$ dplyr --verbose --csv filter "cyl == 8" < mtcars.csv 
------------------------------------------
[input] reading CSV from stdin
command: dplyr::filter(.data, cyl == 8)
>>>> output CSV to stdout
"mpg","cyl","disp","hp","drat","wt","qsec","vs","am","gear","carb"
18.7,8,360,175,3.15,3.44,17.02,0,0,3,2
14.3,8,360,245,3.21,3.57,15.84,0,0,3,4
16.4,8,275.8,180,3.07,4.07,17.4,0,0,3,3
17.3,8,275.8,180,3.07,3.73,17.6,0,0,3,3
15.2,8,275.8,180,3.07,3.78,18,0,0,3,3
10.4,8,472,205,2.93,5.25,17.98,0,0,3,4
10.4,8,460,215,3,5.424,17.82,0,0,3,4
14.7,8,440,230,3.23,5.345,17.42,0,0,3,4
15.5,8,318,150,2.76,3.52,16.87,0,0,3,2
15.2,8,304,150,3.15,3.435,17.3,0,0,3,2
13.3,8,350,245,3.73,3.84,15.41,0,0,3,4
19.2,8,400,175,3.08,3.845,17.05,0,0,3,2
15.8,8,351,264,4.22,3.17,14.5,0,1,5,4
15,8,301,335,3.54,3.57,14.6,0,1,5,8

$ dplyr --verbose --csv --file=mtcars.csv filter "cyl == 8"
------------------------------------------
[input] reading CSV from stdin
command: dplyr::filter(.data, cyl == 8)
>>>> output CSV to stdout
"mpg","cyl","disp","hp","drat","wt","qsec","vs","am","gear","carb"
18.7,8,360,175,3.15,3.44,17.02,0,0,3,2
14.3,8,360,245,3.21,3.57,15.84,0,0,3,4
16.4,8,275.8,180,3.07,4.07,17.4,0,0,3,3
17.3,8,275.8,180,3.07,3.73,17.6,0,0,3,3
15.2,8,275.8,180,3.07,3.78,18,0,0,3,3
10.4,8,472,205,2.93,5.25,17.98,0,0,3,4
10.4,8,460,215,3,5.424,17.82,0,0,3,4
14.7,8,440,230,3.23,5.345,17.42,0,0,3,4
15.5,8,318,150,2.76,3.52,16.87,0,0,3,2
15.2,8,304,150,3.15,3.435,17.3,0,0,3,2
13.3,8,350,245,3.73,3.84,15.41,0,0,3,4
19.2,8,400,175,3.08,3.845,17.05,0,0,3,2
15.8,8,351,264,4.22,3.17,14.5,0,1,5,4
15,8,301,335,3.54,3.57,14.6,0,1,5,8
```

This works under Ubuntu Linux 20.04.3 LTS, using bash 5.0.17

**Comment by SantoshSrinivas79** [comment]
Thanks! That solved it!
